services:
  - type: web
    name: telegram-bot-render
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 7517757393:AAFmAtq_-AXE1wANhDJRtGGuGNpRA0vEaOk
      - key: GROUP_ID
        value: "-1002320071203"
    plan: free
    # Port is now specified in the 'env' section
    env: python
    healthCheckPath: /
